"use client"

import { FileText, Download } from "lucide-react"
import { documents, client } from "@/lib/portal-data"

function downloadDocument(doc: (typeof documents)[number]) {
  const content = [
    `${doc.name}`,
    `Type: ${doc.type}`,
    `Date: ${doc.date}`,
    `Prepared for: ${client.name}`,
    "",
    "This is a placeholder file generated by the Marchetti Stone demo portal.",
    "In production this action would stream the real document from secure storage.",
  ].join("\n")

  const blob = new Blob([content], { type: "text/plain" })
  const url = URL.createObjectURL(blob)
  const a = document.createElement("a")
  a.href = url
  a.download = `${doc.name.replace(/[^\w\- ]/g, "")}.txt`
  document.body.appendChild(a)
  a.click()
  a.remove()
  URL.revokeObjectURL(url)
}

export function DocumentVault() {
  return (
    <div className="rounded-lg border border-border bg-card">
      <div className="border-b border-border px-6 py-4">
        <h1 className="font-serif text-lg font-medium tracking-tight text-foreground">Document Vault</h1>
        <p className="text-sm text-muted-foreground">{documents.length} documents</p>
      </div>
      <ul className="divide-y divide-border/60">
        {documents.map((doc) => (
          <li
            key={doc.name}
            className="flex items-center justify-between gap-4 px-6 py-3.5 hover:bg-secondary/40"
          >
            <div className="flex items-center gap-3">
              <span className="flex h-9 w-9 shrink-0 items-center justify-center rounded-md bg-primary/8 text-primary">
                <FileText className="h-4 w-4" />
              </span>
              <div>
                <p className="text-sm font-medium text-foreground">{doc.name}</p>
                <p className="text-xs text-muted-foreground">
                  {doc.type} · {doc.date} · {doc.size}
                </p>
              </div>
            </div>
            <button
              type="button"
              aria-label={`Download ${doc.name}`}
              onClick={() => downloadDocument(doc)}
              className="flex h-8 w-8 items-center justify-center rounded-md text-muted-foreground transition-colors hover:bg-muted hover:text-foreground"
            >
              <Download className="h-4 w-4" />
            </button>
          </li>
        ))}
      </ul>
    </div>
  )
}
